// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANaSQ1kXr6KSCEgaP7a3wGYCSDFtsZqQI',
    appId: '1:510821241795:web:d6308263b5c0668cb62376',
    messagingSenderId: '510821241795',
    projectId: 'finalapp-7d8c2',
    authDomain: 'finalapp-7d8c2.firebaseapp.com',
    storageBucket: 'finalapp-7d8c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPh3nBQ0U97GjzumTYwOy4svde741AA34',
    appId: '1:510821241795:android:dcc198c1a5a0ad8eb62376',
    messagingSenderId: '510821241795',
    projectId: 'finalapp-7d8c2',
    storageBucket: 'finalapp-7d8c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFg07YQyfllcjlyp2Y6cwKHG6_nURO4NA',
    appId: '1:510821241795:ios:26a379822baa0723b62376',
    messagingSenderId: '510821241795',
    projectId: 'finalapp-7d8c2',
    storageBucket: 'finalapp-7d8c2.appspot.com',
    iosBundleId: 'com.example.finalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFg07YQyfllcjlyp2Y6cwKHG6_nURO4NA',
    appId: '1:510821241795:ios:26a379822baa0723b62376',
    messagingSenderId: '510821241795',
    projectId: 'finalapp-7d8c2',
    storageBucket: 'finalapp-7d8c2.appspot.com',
    iosBundleId: 'com.example.finalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANaSQ1kXr6KSCEgaP7a3wGYCSDFtsZqQI',
    appId: '1:510821241795:web:9408165a38cc2645b62376',
    messagingSenderId: '510821241795',
    projectId: 'finalapp-7d8c2',
    authDomain: 'finalapp-7d8c2.firebaseapp.com',
    storageBucket: 'finalapp-7d8c2.appspot.com',
  );

}